// AUTOGENERATED FILE


#if defined(__x86_64__) || 0
#define GOARCH "amd64"
#define SYZ_REVISION "1f0cebed9eafeec103cfea9ddea323a02af56f27"
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
unsigned syscall_count = 3;
call_t syscalls[] = {
	{"open", 0, (syscall_t)open},
	{"sys_exit", 0, (syscall_t)sys_exit},
	{"sys_wait", 0, (syscall_t)sys_wait},

};
#endif
